//When it comes to the imports, the following just:
//1) imports the Netadata interface to type-check any recieved Metadata Objects
//2) imports the following fonts from next;s built-in functions
//imports our global.css file )applies to all pages/layouts
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//imports the desired variable-name for using the following font/the character set to be
//used (The latin set here)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//same as above for the following font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//this data is used to populate the tags within the <head> of the following pages
//(ie <title> and <meta>)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//this exports the defsault function, which just renders {children} (our nexted content)
//ie page.tsx inside the <body> tag
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
